name: markedit_api
description: An Aqueduct application with a database connection, data model and OAuth 2.0 endpoints.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.8.3 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1
  mailer: ^3.2.1
